### ISSUE TITLE
Get Prep Instructions returning null response

### ISSUE THREAD

**Issue by nafberger** [abuzuhri/Amazon-SP-API-CSharp#372]
something funny when making the call 

amazonConnection.FulFillmentInbound.GetPrepInstructions

amazon sends back the data but it doesnt get deserialized.

![Screenshot_1](https://user-images.githubusercontent.com/26122027/198902101-e785ac14-39fe-4a4e-80eb-68607da31693.png)

**Comment by nafberger** [comment]
it's because response data is not null, not clear what that ,means.

**Comment by nafberger** [comment]
![image](https://user-images.githubusercontent.com/26122027/198902297-18d743e4-067f-4657-8bb5-c27ec62fcf04.png)

**Comment by nafberger** [comment]
@abuzuhri I will check and respond to your comments on the other issues I opened

**Comment by RenzoF** [comment]
@nafberger @abuzuhri this bug was introduced with the RestSharp upgrade.
Restsharp supports JsonSerializer using this nugget RestSharp.Serializers.NewtonsoftJson @nafberger I think if you try adding this package data will already be serialized.
I haven't  tested that much and that's why I haven't done a pull, also not sure if it was ok to add a new package to the project

**Comment by abuzuhri** [comment]
@RenzoF we need to solve this as its Urgent

**Comment by J-W-Chan** [comment]
@RenzoF I've fixed this problem in #380 .Please help us test it

**Comment by RenzoF** [comment]
Thanks, @J-W-Chan I have tested this on a few methods where it was failing before and now seems to be working in 1.5.7

@abuzuhri I think we need a better way of managing the releases as we shouldn't have posted this to live while there were issues pending.

**Comment by nafberger** [comment]
![image](https://user-images.githubusercontent.com/26122027/199857678-8ea47a66-e2f8-4102-be4e-e50d78b8cff4.png)

![image](https://user-images.githubusercontent.com/26122027/199857684-dbbbd336-4162-49d9-ae4b-fe38a212710b.png)

**Comment by nafberger** [comment]
still the same issue, i am on 1.5.8 and the response from the method is still null, although amazon is sending back a proper response

**Comment by nafberger** [comment]
@J-W-Chan 
problem is with this line 

 if (response.StatusCode == HttpStatusCode.OK && !string.IsNullOrEmpty(response.Content) && response.Data == null)

with the get prep instructions call the data comes already pre populated with and entry instantiated response class without any valid data

**Comment by J-W-Chan** [comment]
> 

i think this is amazon sp-api doc error. There is no description of “SKUInboundGuidanceList” in the sp-api document.
![image](https://user-images.githubusercontent.com/6493028/199910240-5572b661-e778-4bdc-99e6-4b2999b5ba81.png)

**Comment by RenzoF** [comment]
Good catch @J-W-Chan I think the docs are not reflecting the models on their repo as it seems to be in here https://github.com/amzn/selling-partner-api-models/blob/784e994d2b9076f7d1e3835828955d2852067027/models/fulfillment-inbound-api-model/fulfillmentInboundV0.json#L97
![image](https://user-images.githubusercontent.com/1706557/199922295-e3a160a2-2073-4a21-93b7-1d621247e977.png)

**Comment by RenzoF** [comment]
Actually, ignore that, that is the response for item guidance, not prep instructions, the issue here is that the prep instructions call was pointing to the wrong endpoint.

**Comment by RenzoF** [comment]
@nafberger Can you test this with the latest code, I have tested on my side and this resolves the issue, though I will leave this open until you confirm it

**Comment by nafberger** [comment]
@RenzoF 
its fixed, huge thanks i am closing issue
